version: '3.1'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - backend
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: 'test'
    volumes:
      - ../database/sql:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    restart: always
    networks:
      - backend
    ports:
      - 9002:8080
  egg:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        DOCKER_BUILD_ARGS: --progress=plain
    image: example/egg:latest
    restart: always
    networks:
      - backend
    ports:
      - 9001:9001
networks:
  backend:
    driver: bridge
